"""
Django settings for src project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import logging.config
import os
from pathlib import Path

from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("APP_SECRET_KEY", default="sample-key")
PGCRYPTO_KEY = config("PGCRYPTO_KEY", default="sample-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)
ENABLE_ADMIN_EMAILS = config("ENABLE_ADMIN_EMAILS", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=Csv(), default="*")

# Allowed host for X_HOST headers
ALLOWED_ORIGINAL_HOST = config("ALLOWED_ORIGINAL_HOST", default="")
X_FRAME_OPTIONS = "DENY"

# Email config
EMAIL_BACKEND = config("EMAIL_BACKEND", default="pg.services.emails.backend.EmailBackend")
EMAIL_FROM_EMAIL = config("EMAIL_FROM_EMAIL", default="info@pgtry.com")
EMAIL_FROM_NAME = config("EMAIL_FROM_NAME", default="P&G")
VF_EMAIL_ENDPOINT = config("VF_EMAIL_ENDPOINT")
VF_EMAIL_USERNAME = config("VF_EMAIL_USERNAME")
VF_EMAIL_PASSWORD = config("VF_EMAIL_PASSWORD")
VFIRST_SMS_API_URL = config("VFIRST_SMS_API_URL")
VFIRST_SMS_API_KEY = config("VFIRST_SMS_API_KEY")
OTP_TIMEOUT_SECONDS = 10 * 60
OTP_LENGTH = 4
SEND_SMS = not DEBUG


SITE_ID = 1

URL_PREFIX = ""
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Thirdpaty
    "django_extensions",
    "rest_framework",
    # custom
    "pg", #internal package for P&G related dependencies
    "core",
    # Keep this at the end
    "django_cleanup.apps.CleanupConfig",
]

MIDDLEWARE = [
    "pg.middleware.DisallowedHostMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [str(Path(BASE_DIR, "src/templates"))],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": config("POSTGRES_DB", default=None),
        "USER": config("POSTGRES_USER", default=None),
        "PASSWORD": config("POSTGRES_PASSWORD", default=None),
        "HOST": config("DB_HOST", default=None),
        "PORT": config("DB_PORT", default=5432),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


MEDIA_ROOT = BASE_DIR / "media"
STATIC_ROOT = BASE_DIR / "assets"

STATICFILES_DIRS = [
    BASE_DIR / "static",
    MEDIA_ROOT,
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

STATIC_URL = "/assets/"
MEDIA_URL = "/media/"

if not DEBUG:
    SET_HTTP_X_FORWARDED_HOST = config(
        "SET_HTTP_X_FORWARDED_HOST", default=False, cast=bool
    )
    USE_X_FORWARDED_HOST = SET_HTTP_X_FORWARDED_HOST
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

    def force_download_pdfs(headers, path, url):  # noqa
        if path.endswith(".pdf"):
            headers["Content-Disposition"] = "attachment"

    WHITENOISE_ADD_HEADERS_FUNCTION = force_download_pdfs

    COMPRESS_STORAGE = STATICFILES_STORAGE

    AZURE_OVERWRITE_FILES = True
    AZURE_URL_EXPIRATION_SECS = 3600

    STATIC_URL = f"/{URL_PREFIX}/assets/"
    MEDIA_URL = f"/{URL_PREFIX}/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Logging
LOGGING_CONFIG = None
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(levelname)-8s %(asctime)s [%(request_id)s]  %(process)s --- "
            "%(lineno)-8s [%(name)s] %(funcName)-24s : %(message)s"
        }
    },
    "filters": {
        "require_debug_false": {"()": "django.utils.log.RequireDebugFalse"},
        "require_debug_true": {"()": "django.utils.log.RequireDebugTrue"},
        "request_id": {"()": "log_request_id.filters.RequestIDFilter"},
        "require_mail_true": {"()": "pg.log.RequireMailTrue"},
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "filters": ["request_id"],
        },
        "mail_admins_custom": {
            "level": "ERROR",
            "filters": ["require_mail_true", "request_id"],
            "class": "pg.log.AdminEmailHandler",
            "include_html": True,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "": {
            "level": config("LOG_LEVEL", default="INFO"),
            "handlers": [
                "console",
            ],
            "propagate": False,
        },
    },
}
logging.config.dictConfig(LOGGING)

# Custom config
AUTH_USER_MODEL = "core.User"


# Rest framework
REST_FRAMEWORK = {
    "DATE_INPUT_FORMATS": ["%d-%m-%Y", "%Y-%m-%d"],
    "DEFAULT_FILTER_BACKENDS": ("django_filters.rest_framework.DjangoFilterBackend",),
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {"anon": "60/minute", "user": "60/minute"},
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
}

# Redis config
REDIS_CONN_STRING = config("REDIS_CONN_STRING", default="redis://localhost:6379")
REDIS_CACHE_STORE = config("REDIS_CACHE_STORE", cast=int, default=0)


# Redis Cache backend
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_CONN_STRING}/{REDIS_CACHE_STORE}",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "REDIS_CLIENT_KWARGS": {"ssl": True},
        },
    },
    "dummy": {"BACKEND": "django.core.cache.backends.dummy.DummyCache"},
}





if DEBUG:
    INTERNAL_IPS = ("127.0.0.1", "localhost")
    MIDDLEWARE += ("debug_toolbar.middleware.DebugToolbarMiddleware",)
    INSTALLED_APPS += ("debug_toolbar", "sslserver")
else:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_HSTS_SECONDS = 60 * 60
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"
    SECURE_BROWSER_XSS_FILTER = True
