version: '3.8'

services:
    oralb-shiny-clean-prod:
        image: pgtryprodregistry.azurecr.io/pgtry-{app_name}-prod:main
        env_file: .azure-prod.env
        build:
            context: ../../../
            args:
                - USE_AZURE_ENVIRONMENT=$USE_AZURE_ENVIRONMENT
                - USE_BLOB_STORAGE=$USE_BLOB_STORAGE
                - AZ_CDN_DOMAIN=$AZ_CDN_DOMAIN
                - AZ_PRIVATE_STORAGE_CONTAINER=$AZ_PRIVATE_STORAGE_CONTAINER
                - AZ_PUBLIC_STORAGE_CONTAINER=$AZ_PUBLIC_STORAGE_CONTAINER
                - AZ_STORAGE_ACCOUNT_NAME=$AZ_STORAGE_ACCOUNT_NAME
                - AZ_STORAGE_KEY=$AZ_STORAGE_KEY
        ports:
            - "8000:8000"
